import { AnimationMode, RenderMode, Language } from "./types";

export const DENSITY_SETS = {
  // Strategy: Remove middle-density noise chars (-, +, =, ^, ~)
  // Strategy: Add trailing spaces to ensure "near-white" or "near-black" maps to empty space.
  
  STANDARD: "Ñ@#W$9876543210?!abc;:+       ",
  
  SIMPLE: "@%#*+:    ",
  
  // Ultra-clean high detail set. 
  // REMOVED: - _ = + < > ^ ~ " ' . ,
  // ADDED: Extra spaces at the end to act as a noise gate.
  COMPLEX: "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?I;:       ",
  
  BLOCKS: "█▓▒░ ",
};

export const DEFAULT_SETTINGS = {
  resolution: 120, // Width in chars
  density: DENSITY_SETS.COMPLEX,
  color: '#ffffff', // Default to white
  backgroundColor: '#000000',
  transparentBackground: false,
  contrast: 1.0,
  animationSpeed: 1.0,
  animationIntensity: 1.0,
  animationMode: AnimationMode.STATIC,
  renderMode: RenderMode.ASCII,
  fontSize: 10,
  invert: false,
  showLabels: false,
  extractionThreshold: 20, // Default variance threshold for subject extraction
  motionScript: "const phase = (x * 0.05) + (y * 0.05);\nreturn [\n  Math.sin(t + phase) * i * 2,\n  Math.cos(t * 1.2 + phase) * i * 2\n];"
};

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    // App.tsx
    importText: "Import",
    dropText: "DROP MEDIA TO IMPORT",
    generatorModule: "GENERATOR MODULE",
    inputPromptPlaceholder: "INPUT PROMPT...",
    initGeneration: "INIT GENERATION",
    processImage: "PROCESS IMAGE",
    removeBg: "AI REMOVE BACKGROUND",
    chromaKey: "MANUAL CHROMA KEY",
    projectFiles: "PROJECT FILES",
    online: "ONLINE",
    viewportMain: "VIEWPORT MAIN",
    res: "RES",
    mode: "MODE",
    static: "STATIC",
    live: "LIVE",
    noSignal: "NO SIGNAL",
    inspector: "INSPECTOR",
    items: "ITEMS",
    mem: "MEM",
    
    // Controls.tsx
    visual: "VISUAL",
    style: "STYLE",
    fx: "FX",
    gridMetrics: "GRID METRICS",
    resolution: "RESOLUTION",
    cellSize: "CELL SIZE",
    signalProcessing: "SIGNAL PROCESSING",
    contrast: "CONTRAST",
    invertSignal: "INVERT SIGNAL",
    alpha0: "Alpha: 0",
    alpha1: "Alpha: 1",
    renderKernel: "RENDER KERNEL",
    text: "TEXT",
    bead: "BEAD",
    pixel: "PIXEL",
    voxel: "VOXEL",
    colorChannel: "COLOR CHANNEL",
    fgColor: "FG_COLOR",
    bgColor: "BG_COLOR",
    bgNull: "NULL",
    characterMap: "CHARACTER MAP",
    mapHighDetail: "MAP_A: HIGH_DETAIL",
    mapStandard: "MAP_B: STANDARD",
    mapMinimal: "MAP_C: MINIMAL",
    mapBlocks: "MAP_D: SOLID_BLOCKS",
    physicsEngine: "PHYSICS ENGINE",
    dynamic: "DYNAMIC",
    timeScale: "TIME SCALE",
    amplitude: "AMPLITUDE",
    edgeThreshold: "EDGE THRESHOLD",
    openGeneticLab: "Open Genetic Lab",
    neuralScripting: "Neural Scripting",
    enterPrompt: "Enter natural language prompt...",
    
    // AsciiRenderer
    processing: "Processing Image...",
    saveImage: "Save Image",
    copyText: "Copy Text",
    copied: "Copied!",
    colorPalette: "Color Palette",
    beadsCount: "beads",
    colors: "colors",
    clickToHighlight: "Click to highlight",

    // ChromaKeyModal
    superKeyEditor: "Super Key Editor",
    removeBgCrop: "Remove background & Crop",
    colorPicker: "Color Picker",
    cropCut: "Crop / Cut",
    selectedColor: "Selected Color",
    tolerance: "Tolerance",
    softness: "Softness",
    cropArea: "Crop Area",
    clearCrop: "Clear Crop",
    cropInstruction: "Drag on the image to select the area you want to keep. Everything outside the box will be removed.",
    saveCropped: "Save Cropped Selection",
    saveImageSimple: "Save Image",
    resetAll: "Reset All",

    // EvolutionStage
    evolutionLab: "Evolution Lab",
    gen: "Gen",
    selectMutation: "Select the best mutation",
    exit: "Exit",
    selectBreed: "Select & Breed",
    saveOne: "Save this one",
    reseedPopulation: "Reseed Population:",
    runner: "Runner",
    jumper: "Jumper",
    chaos: "Chaos",
  },
  zh: {
     // App.tsx
    importText: "导入",
    dropText: "拖放媒体以导入",
    generatorModule: "生成模块",
    inputPromptPlaceholder: "输入提示词...",
    initGeneration: "开始生成",
    processImage: "图像处理",
    removeBg: "AI 移除背景",
    chromaKey: "手动抠图",
    projectFiles: "项目文件",
    online: "在线",
    viewportMain: "主视图",
    res: "分辨率",
    mode: "模式",
    static: "静态",
    live: "实时",
    noSignal: "无信号",
    inspector: "检查器",
    items: "项目",
    mem: "内存",

    // Controls.tsx
    visual: "视觉",
    style: "样式",
    fx: "特效",
    gridMetrics: "网格指标",
    resolution: "分辨率",
    cellSize: "单元格大小",
    signalProcessing: "信号处理",
    contrast: "对比度",
    invertSignal: "反转信号",
    alpha0: "透明度: 0",
    alpha1: "透明度: 1",
    renderKernel: "渲染内核",
    text: "文本",
    bead: "拼豆",
    pixel: "像素",
    voxel: "体素",
    colorChannel: "色彩通道",
    fgColor: "前景色",
    bgColor: "背景色",
    bgNull: "空",
    characterMap: "字符映射",
    mapHighDetail: "映射 A: 高细节",
    mapStandard: "映射 B: 标准",
    mapMinimal: "映射 C: 极简",
    mapBlocks: "映射 D: 实心块",
    physicsEngine: "物理引擎",
    dynamic: "动态",
    timeScale: "时间缩放",
    amplitude: "振幅",
    edgeThreshold: "边缘阈值",
    openGeneticLab: "打开遗传实验室",
    neuralScripting: "神经脚本",
    enterPrompt: "输入自然语言提示...",

    // AsciiRenderer
    processing: "正在处理图像...",
    saveImage: "保存图像",
    copyText: "复制文本",
    copied: "已复制!",
    colorPalette: "调色板",
    beadsCount: "颗",
    colors: "种颜色",
    clickToHighlight: "点击颜色以高亮",

    // ChromaKeyModal
    superKeyEditor: "超级键控编辑器",
    removeBgCrop: "移除背景 & 裁剪",
    colorPicker: "吸管工具",
    cropCut: "裁剪 / 切割",
    selectedColor: "选定颜色",
    tolerance: "容差",
    softness: "柔化",
    cropArea: "裁剪区域",
    clearCrop: "清除裁剪",
    cropInstruction: "在图像上拖动以选择要保留的区域。框外的所有内容都将被删除。",
    saveCropped: "保存裁剪选区",
    saveImageSimple: "保存图像",
    resetAll: "全部重置",

    // EvolutionStage
    evolutionLab: "进化实验室",
    gen: "代",
    selectMutation: "选择最佳变异",
    exit: "退出",
    selectBreed: "选择 & 繁育",
    saveOne: "保存此变异",
    reseedPopulation: "重置种群:",
    runner: "奔跑者",
    jumper: "跳跃者",
    chaos: "混沌",
  }
};